services:
  - type: web
    name: tenly-api
    runtime: node
    rootDir: server
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npx tsc prisma/seed.ts --outDir dist --esModuleInterop --skipLibCheck --resolveJsonModule --module commonjs --target ES2020
    startCommand: npx prisma db push --force-reset && node dist/seed.js && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: EMAIL_TRANSPORT
        value: console
      - key: CLIENT_URL
        sync: false
